# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04

all:
  children:
    docker_swarm_nodes:
      hosts:
        docker_swarm_node_1:
          ansible_host: 178.62.184.18
          ansible_user: root
          swarm_head: yes
#        docker_swarm_node_2:
#          ansible_host:
#          ansible_user: root
#          swarm_head: no



# docs: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html