# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04

all:
  children:
    docker_swarm_nodes:     # at least 1 leader and ODD number of managers (leader is a manager too)!
      hosts:
        docker_swarm_node_1: # leader must be first in alphabetical order here bug: https://github.com/ansible/ansible/issues/34861
          ansible_host: 178.62.184.188
          ansible_user: root
          swarm_role: leader

#        docker_swarm_node_2:
#          ansible_host: 178.62.184.18
#          ansible_user: root
#          swarm_role: manager

#        docker_swarm_node_3:
#          ansible_host: 178.62.180.137
#          ansible_user: root
#          swarm_role: worker



# docs: https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html