# Simple services health checkup for paranoics and occasional use
---
- name: Docker node Healthchecks
  hosts: docker*
  remote_user: '{{ _remote_user }}'

  tasks:
    - shell: systemctl status docker
      when: "'docker' in inventory_hostname"
      ignore_errors: yes

    - service:
        name: docker
        state: started
      when: "'docker' in inventory_hostname"
      ignore_errors: yes

    - debug:
        var: swarm_info

    - debug:
        var: swarm_leader_host