# Basic Docker install and swarm init
#
---
- name: Install Docker Engine
  hosts: docker*
  max_fail_percentage: 1
  order: sorted
  remote_user: root

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Additional packages
      apt: "pkg={{ item }} state=latest"
      with_items: '{{ _addons }}'
      when: _addons is defined

# https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html

    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"
        dispatcher_heartbeat_period: "{{ swarm_dispatcher_heartbeat_period }}"
        election_tick: "{{ swarm_raft_election_tick }}"
        heartbeat_tick: "{{ swarm_raft_heartbeat_tick }}"
      when: swarm_role == 'leader'

    - set_fact:
        swarm_leader_host: "{{ ansible_host }}"

    - name: Inspect swarm
      docker_swarm_info:
        nodes: yes
        services: yes
        tasks: yes
      register: swarm_info
      when: swarm_role == 'leader'


#  handlers:
#    - name: restart nginx
#      service: name=nginx state=restarted
