# Docker config files provisioning
---
- name: Prepare docker hosts
  hosts: docker*
  remote_user: '{{ _remote_user }}'
  become: false

  roles:
#    - role: nickhammond.logrotate
#      become: true
#
#      logrotate_scripts:
#        - name: '{{ _site.name }}'
#          path: '{{ _site.logs_path }}/*.log'
#          options:
#            - daily
#            - rotate 7
#            - missingok
#            - compress
#            - delaycompress
#            - notifempty
#            - create 0666 {{ _remote_user }} {{ _remote_user }}
#          when: _site.logs_path is defined
#
  tasks:

    - name: "Swarm info debug"
      debug:
        var:

#    - name: Join a swarm cluster as a manager
#      docker_swarm:
#        state: join
#        advertise_addr: ansible_host
#        join_token: #SWMTKN-1--xxxxx
#        remote_addrs: [  ]
#      when: not swarm_head and swarm_manager
#
#    - name: Join a swarm cluster as a worker
#      docker_swarm:
#        state: join
#        advertise_addr: ansible_host
#        join_token: #SWMTKN-1--xxxxx
#        remote_addrs: [  ]
#      when: not swarm_head and swarm_worker

#  handlers:
#    - name: restart nginx
#      become: true
#      service: name=nginx state=restarted